### ISSUE TITLE
popin with active background contents

### ISSUE THREAD

**Issue by DylannCordel** [vast-engineering/jquery-popup-overlay#18]
Hello,

When a popin is created with those options :

``` javascript
    {
        background:false,
        blur:false,
    }
```

Background elements (links for exemple) are inactive because wrapper is in front of these. It could be nice to add an option to have a not "fixed" wrapper to keep an active background and not have to hack this with CSS rules like this :

``` css
    #buddies .popup_wrapper{
        height:0px !important;
        width:0px !important;
        position:inherit !important;
    }
```
